## to set logging level of spring application to trace,debug,info,warn,error,off
logging.level.org.springframework=DEBUG

## To Select environment specific profile
spring.profiles.active=prod

## enabling h2 in memory DB console and giving predefine url for db connection
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

## to show the sql used in logs when using JPA
spring.jpa.show-sql=true

## To enable all the Actuator endpoints
management.endpoints.web.exposure.include=*